# Generated by Django 3.0.3 on 2020-04-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ydl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('vdeo', models.FileField(upload_to='media/%y/%m/%d')),
            ],
        ),
    ]
