# Generated by Django 3.0.3 on 2020-04-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ydl',
            name='vdeo',
        ),
        migrations.AlterField(
            model_name='ydl',
            name='link',
            field=models.CharField(max_length=250),
        ),
    ]
